### ISSUE TITLE
Error in ./anonParallel_java.sh - No such file or directory

### ISSUE THREAD

**Issue by sidsvash26** [sinantie/NeuralAmr#12]
I have "LDC2015E86" data and I am trying to run the pre-processing on that data.

I changed the following line in _settings.properties_ as suggested in the directions to point to the correct data.
`amr.down.base            = data/alignments/split/`

Then I ran the following to run the server:
`./nerServer.sh&`

which outputs:
```
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Loading POS tagger from lib/models/pos-tagger/english-left3words-distsim.tagger ... done [0.6 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from lib/models/ner/english.all.3class.distsim.crf.ser.gz ... done [2.6 sec].
NER Server listening on port 4444
```

Then I ran:
`./anonParallel_java.sh`
which gives me the following output:
```
Read 147 NE concepts from propreties.
Read 32 Quantity concepts from propreties.
Read 4 Value concepts from propreties.
Read 14 Date roles from propreties.
Read 45 concepts/roles to filter from propreties.
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Loading POS tagger from lib/models/pos-tagger/english-left3words-distsim.tagger ... done [0.6 sec].
Adding annotator lemma
Reading JAMR alignments from null
Exception in thread "main" java.lang.NullPointerException
	at util.utils.Utils.readLines(Utils.java:37)
	at util.utils.Utils.readLines(Utils.java:42)
	at util.corpus.AmrCorpus.readJamrAlignments(AmrCorpus.java:300)
	at util.corpus.AmrCorpus.preLoadLinearizeDictionaries(AmrCorpus.java:115)
	at util.corpus.AmrCorpus.preprocess(AmrCorpus.java:85)
	at util.apps.Preprocess.execute(Preprocess.java:17)
	at util.apps.Preprocess.main(Preprocess.java:23)
mv: rename tmp//*.txt to data/little-prince-meta/*.txt: No such file or directory
mv: rename tmp//*.obj.gz to data/little-prince-meta/*.obj.gz: No such file or directory
cut: data/little-prince-meta/test-dfs-linear.txt: No such file or directory
cut: data/little-prince-meta/dev-dfs-linear.txt: No such file or directory
cut: data/little-prince-meta/training-dfs-linear.txt: No such file or directory
cut: data/little-prince-meta/dev-dfs-linear.txt: No such file or directory
cut: data/little-prince-meta/test-dfs-linear.txt: No such file or directory
cut: data/little-prince-meta/training-dfs-linear.txt: No such file or directory
cut: data/little-prince-meta/dev-dfs-linear.txt: No such file or directory
cut: data/little-prince-meta/test-dfs-linear.txt: No such file or directory
cut: data/little-prince-meta/training-amr-nl-alignments-seq.txt: No such file or directory
cut: data/little-prince-meta/dev-amr-nl-alignments-seq.txt: No such file or directory
cut: data/little-prince-meta/dev-nl.txt: No such file or directory
cut: data/little-prince-meta/test-nl.txt: No such file or directory
cp: data/little-prince-meta/training-amr-nl-alignments.txt: No such file or directory
cp: data/little-prince-meta/dev-anonymized-alignments.txt: No such file or directory
cp: data/little-prince-meta/test-anonymized-alignments.txt: No such file or directory
cp: data/little-prince-meta/dev-nl.txt: No such file or directory
cp: data/little-prince-meta/test-nl.txt: No such file or directory
cp: data/little-prince-meta/dev-raw-amr-ids.txt: No such file or directory
cp: data/little-prince-meta/test-raw-amr-ids.txt: No such file or directory
```

My understanding is that the following variables:
```
DATA_DIR=data/little-prince-meta
OUT_DIR=data/little-prince-input_data
```
in the _anonParallel_java.sh_ file point to the directories in which new files will be created, but I am getting the above errors. 

Could you please suggest what am I missing?

**Comment by sodawater** [comment]
I meet the same problem. Have you solved it?
