### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by freesunshine0316** [sinantie/NeuralAmr#6]
When I ran ./anonParallel_java.sh, I got the following errors:

null
java.lang.ClassNotFoundException: uk.ac.ed.gen.corpus.AmrCorpus
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at util.apps.Application.init(Application.java:33)
        at util.apps.Application.<init>(Application.java:26)
        at util.apps.Preprocess.<init>(Preprocess.java:11)
        at util.apps.Preprocess.main(Preprocess.java:22)
Exception in thread "main" java.lang.NullPointerException
        at util.apps.Preprocess.execute(Preprocess.java:17)
        at util.apps.Preprocess.main(Preprocess.java:23)

**Comment by freesunshine0316** [comment]
It's because I forgot to run "./rebuild_AmrUtils.sh" after checking out the latest version.
